### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ghost** [jplein/tmux-term-drawer#1]
Had an issue at first using tmux 3.1, as well as running the program without the full path in the tmux config.

But this was a great idea and I appreciate the tool, I will be using this for the foreseeable future! 👍

**Comment by jplein** [comment]
Thank you, that is useful feedback. I've only ever used it on tmux 3.3a, but the documentation doesn't give a required version. I'll update the README for now to make it clear that 3.3a is the required version, and I'll see if I find a way to get it working on versions before 3.3.

I'm happy that you are using it! I haven't tried to publicize this repo outside of my friends, and it makes me very happy that someone besides me is using it. Cheers!
